version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: gearup-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    networks:
      - gearup_network
    volumes:
      - gearup_data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5255:8080"
    environment:
      KestrelCertificates__Development__Password: ${KestrelCertificates__Development__Password}
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      Jwt__Issuer: ${Jwt__Issuer}
      Jwt__Audience: ${Jwt__Audience}
      Jwt__AccessToken_SecretKey: ${Jwt__AccessToken_SecretKey}
      Jwt__EmailVerificationToken_SecretKey: ${Jwt__EmailVerificationToken_SecretKey}
      SendGridApiKey: ${SendGridApiKey}
      FromEmail: ${FromEmail}
      ClientUrl: ${ClientUrl}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - db
    networks:
      - gearup_network
    restart: on-failure


volumes:
  gearup_data:

networks:
    gearup_network:




